import type { Metadata } from "next";
import { ISbStoriesParams, getStoryblokApi, storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokProvider from "../components/StoryblokProvider";
import { agrandir, reckless } from "../../styles/fonts";
import "./globals.css";
import Navigation from "../components/Navigation";
import Footer from "@/components/Footer";

storyblokInit({
  accessToken: process.env.STORYBLOK_API_TOKEN,
  use: [apiPlugin],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData = await fetchNavData();

  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${agrandir.variable} ${reckless.variable}`}>
          <Navigation navData={navData} />
          {children}
          <Footer navData={navData} />
        </body>
      </html>
    </StoryblokProvider>
  );
}

async function fetchNavData() {
  return getStoryblokApi().get(`cdn/stories/global-settings/navigation`, { 
    version: "draft" 
  } );
}