import type { Metadata } from "next";
import { ISbStoriesParams, getStoryblokApi, storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokProvider from "../components/StoryblokProvider";
import { agrandir, reckless } from "../../styles/fonts";
import "./globals.css";
import Navigation from "../components/Navigation";
import Footer from "@/components/Footer";
import { draftMode } from "next/headers";

storyblokInit({
  accessToken: process.env.STORYBLOK_API_TOKEN,
  use: [apiPlugin],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData = await fetchNavData();

  const { isEnabled } = draftMode();

  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${agrandir.variable} ${reckless.variable}`}>
          <Navigation navData={navData} />
          {children}
          { isEnabled && <div style={{
            'position': 'fixed',
            'bottom': '0',
            'right': '0',
            'background': 'red',
            'color': 'white',
          }}>Draft Mode</div>}
          <Footer navData={navData} />
        </body>
      </html>
    </StoryblokProvider>
  );
}

async function fetchNavData() {
  return getStoryblokApi().get(`cdn/stories/global-settings/navigation`, { 
    version: "draft" 
  } );
}